---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver:
      network:
        - ["private_network", {ip: "192.168.33.40"}]

suites:
  - name: confluence-jira-crowd
    run_list:
      - recipe[confluence-jira-crowd]
    attributes:
      mysql:
        server_root_password: iloverandompasswordsbutthiswilldo
        server_repl_password: iloverandompasswordsbutthiswilldo
        server_debian_password: iloverandompasswordsbutthiswilldo
