---
driver:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver:
      name: digitalocean
      image_id: 3101045
      flavor_id: 66
      region_id: 4
      ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
      ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
    run_list:
      - recipe[apt]

suites:
  - name: confluence-jira-crowd
    driver:
      server_name: confluence-jira-crowd-server
    run_list:
      - recipe[confluence-jira-crowd]
    attributes:
      mysql:
        server_root_password: iloverandompasswordsbutthiswilldo
        server_repl_password: iloverandompasswordsbutthiswilldo
        server_debian_password: iloverandompasswordsbutthiswilldo
